### ISSUE TITLE
doc: Missing documentation for extras in latest

### ISSUE THREAD

**Issue by qpoterek** [sertit/sertit-utils#20]
The documentation for the latest version of `sertit-utils` is missing sections for extras, such as `rasters`, `rasters-rio` and `vectors`, even though they still exist in the source code. They do not appear when using the search function either, except for mentions in the change logs.

Stable version
![image](https://github.com/user-attachments/assets/2e930a73-0308-4f17-ab87-df1b6c4a85be)

Latest version
![image](https://github.com/user-attachments/assets/c0f08c9f-f2ca-453a-8032-d04214bc2190)

**Comment by remi-braun** [comment]
Solved by 5195330cb069ffb5737ef90fea494103f787e063
