### ISSUE TITLE
Allow setting SNAP logging level

### ISSUE THREAD

**Issue by guillemc23** [sertit/sertit-utils#25]
I was testing different configurations of the SNAP and GPT settings in order to debug an EOReader issue. I wasn't able to change my logging to debug until I saw this line here:

https://github.com/sertit/sertit-utils/blob/003da65767a942812d31014913e499bf41c79089/sertit/snap.py#L122

I think it might be a good idea to let the user specify the logging level cause this line here is overriding the SNAP or GPT options set at `snap.properties` or `gpt.vmoptions`, the same way as we're allowing to set, for example, maximum memory usage.

It could be a great approach to set the same logging level as in the Python script, or just by setting an environment variable as `SNAP_LOG_LEVEL` or something similar.

So far, I had to manually set it as follows in `eoreader/products/sar/sar_product.py`:
```python
cmd_list = snap.get_gpt_cli(
    pp_graph,
    [
        f"-Pfile={strings.to_cmd_string(prod_path)}",
        f"-Pcalib_pola={strings.to_cmd_string(band.name)}",
        f"-Pdem_name={strings.to_cmd_string(dem_name.value)}",
        f"-Pdem_path={strings.to_cmd_string(dem_path)}",
        f"-Pcrs={self.crs()}",
        f"-Pres_m={pixel_size}",
        f"-Pres_deg={res_deg}",
        f"-Pout={strings.to_cmd_string(pp_dim)}",
        f"-Dsnap.log.level=DEBUG",
    ],
    display_snap_opt=LOGGER.level == logging.DEBUG,
)
```

**Comment by remi-braun** [comment]
You are right! Never had this usecase before, but it'll be very easy to implement.

**Comment by remi-braun** [comment]
Done, released in 1.43.2

**Comment by guillemc23** [comment]
This was an easy one 😉 thank you!

**Comment by remi-braun** [comment]
Use `SERTIT_UTILS_SNAP_LOG_LEVEL` to modify the value
