### ISSUE TITLE
Dependencies don't match between requirements.txt and setup.py

### ISSUE THREAD

**Issue by DManowitz** [sertit/sertit-utils#9]
**Describe the bug**
There are requirements listed in the `requirements.txt` file (such as `shapely >=2.0.0`) that are not present in the `setup.py` file.  Since   the `requirements.txt` file is not used by the `setup.py` file, I believe this can cause issues with enforcing dependencies.

**Code To Reproduce**
CLI commands or Python code snippet to reproduce the bug

```python
```

**Output**
Compete output obtained with maximal verbosity.

**Environment:**
 - Python version: `python --version`
 - sertit-utils version: `import sertit; sertit.__version__`

**Additional context**
Add any other context about the bug here.

**Comment by remi-braun** [comment]
Hey,

Thanks for this, I'll update it 😄
